services:
  lightspot-skywalking-banyandb:
    image: apache/skywalking-banyandb:0.10.0
    container_name: lightspot-skywalking-banyandb
    command: standalone
    environment:
      TZ: Asia/Shanghai
    ports:
      - "17912:17912"
      - "17913:17913"
    volumes:
      - lightspot_skywalking_banyandb_010_data:/data
    networks:
      - lightspot-observability

  lightspot-skywalking-oap:
    image: apache/skywalking-oap-server:10.4.0-java17
    container_name: lightspot-skywalking-oap
    restart: on-failure
    environment:
      SW_STORAGE: banyandb
      SW_STORAGE_BANYANDB_TARGETS: lightspot-skywalking-banyandb:17912
      SW_CLUSTER: standalone
      TZ: Asia/Shanghai
    ports:
      - "11800:11800"
      - "12800:12800"
    depends_on:
      - lightspot-skywalking-banyandb
    networks:
      - lightspot-observability

  lightspot-skywalking-ui:
    image: apache/skywalking-ui:10.4.0-java17
    container_name: lightspot-skywalking-ui
    restart: on-failure
    environment:
      SW_OAP_ADDRESS: http://lightspot-skywalking-oap:12800
      TZ: Asia/Shanghai
    ports:
      - "18080:8080"
    depends_on:
      - lightspot-skywalking-oap
    networks:
      - lightspot-observability

networks:
  lightspot-observability:
    name: lightspot-observability

volumes:
  lightspot_skywalking_banyandb_010_data:
