dubbo.application.name=Lightspot-live-user-provider
dubbo.application.register-mode=instance
dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.scan.base-packages=org.Lightspot.live.user.provider.rpc
dubbo.server=true
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1
